camel.main.name=mcp-icp-motoko-kamelet
camel.component.kamelet.location=classpath*:kamelets
camel.main.routesIncludePattern=classpath*:kamelets/*.kamelet.yaml

camel.route-template[0].template-id=icp-mcp-rest-service
camel.route-template[0].route-id=icpMcpRestKamelet
camel.route-template[0].restComponent=undertow
camel.route-template[0].restHost=0.0.0.0
camel.route-template[0].restPort=3001
camel.route-template[0].restContextPath=/mcp
camel.route-template[0].toolsCallBean=icpBusinessToolsCall
camel.route-template[0].replicaUrl={{sample.ic.location}}
camel.route-template[0].canisterId={{sample.ic.canister}}
camel.route-template[0].didResource=/candid/motoko-sample.did
camel.route-template[0].defaultPojoClass=org.ic4j.sample.mcp.SampleEntryPojo